builds:
  - main: ./shoes-lxd/main.go
    id: "lxd"
    binary: shoes-lxd
    goos:
      - linux
  - main: ./shoes-openstack/main.go
    id: "openstack"
    binary: shoes-openstack
    goos:
      - linux
