builds:
  - dir: shoes-lxd
    id: "lxd"
    binary: shoes-lxd
    goos:
      - linux
    goarch:
      - amd64
  - dir: shoes-openstack
    id: "openstack"
    binary: shoes-openstack
    goos:
      - linux
    goarch:
      - amd64
