builds:
  - dir: shoes-lxd
    id: "lxd"
    binary: shoes-lxd
    goos:
      - linux
    goarch:
      - amd64
  - dir: shoes-openstack
    id: "openstack"
    binary: shoes-openstack
    goos:
      - linux
    goarch:
      - amd64
archives:
  - builds:
    - shoes-lxd
    - shoes-openstack
    format: binary
