name: build
on:
  push:
    branches:
      - "**"

jobs:
  build-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - shoes-lxd
          - shoes-openstack
          - shoes-aws
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: build check
        run: |
          cd ${{ matrix.target }}
          go build -o ${{ matrix.target }} .
      - name: go test
        run: |
          cd ${{ matrix.target }}
          go test -v ./...
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
      - name: Run tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
