name: Build image
on:
  workflow_dispatch:
  push:

jobs:
  build-lxd:
    runs-on: ubuntu-latest
    steps:
      - uses: whywaita/setup-lxd@v1
      - name: setup-packer
        run: |
          sudo apt-get install -y wget unzip
          sudo curl -L -O https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
          sudo unzip packer_1.7.0_linux_amd64.zip
          sudo mv ./packer /tmp/packer
      - uses: actions/checkout@v2
      - name: Delete unused file
        run: |
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/*
          sudo rm -rf /var/lib/docker/*
          # ignore /usr/share/dpkg
          ls /usr/share/ | grep -v dpkg | xargs -I%% sudo rm -rf /usr/share/%%

      - name: Download whywaita/virtual-environments-lxd
        id: download
        run: |
          set -xeu
      
          artifact_download_url=$(curl https://api.github.com/repos/whywaita/virtual-environments-lxd/actions/artifacts | jq '.artifacts | sort_by(.created_at) | reverse' | jq '.[0] | .archive_download_url' | tr -d '"')
          curl -L -u whywaita:${{ secrets.GITHUB_TOKEN }} ${artifact_download_url} -o virtual-environments-lxd.zip

          unzip virtual-environments-lxd.zip
          unzip artifact.zip
          echo "::set-output name=filename::$(basename $(ls _output/*.tar.gz))"
      - name: Import virtual-environments
        run: |
          lxc image import _output/${{ steps.download.outputs.filename }} --alias virtual-environments-lxd
          rm -rf virtual-environments-lxd.zip artifact.zip _output/*


      - name: packer validate packer.json
        run: |
          cd shoes-lxd/images
          /tmp/packer validate -syntax-only ubuntu2004.json
      - name: packer build packer.json
        run: |
          cd shoes-lxd/images
          /tmp/packer build ubuntu2004.json
        env:
          PACKER_LOG: 1


      - name: Export image
        id: export
        run: |
          lxc image export virtual-environments-focal-myshoes ./_output
          echo "::set-output name=artifact::$(basename $(ls *.tar.gz))"
      - name: Compress image
        run: |
          zip -m ./_output/artifact.zip ./_output/*.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: virtual-environments-focal-lxd-myshoes
          path: ./_output/*.zip
          retention-days: 5

      - name: Run tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
