name: build
on:
  push:
    branches:
      - "**"

jobs:
  build-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - shoes-lxd
          - shoes-openstack
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
        run: |
          cd ${{ matrix.target }}
          go build -o ${{ matrix.target }} .

  goreleaser-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: goreleaser check
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
