name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - shoes-lxd
          - shoes-openstack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: release binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p _output
          cd ${{ matrix.target }}
          go build -o ../_output .
          cd ../

          GO111MODULE=off GOBIN=$(pwd)/bin go get github.com/tcnksm/ghr
          TAG_NAME=${GITHUB_REF##*/}

          bin/ghr -replace -draft ${TAG_NAME} _output
